services:
  # Static Site for Frontend
  - type: web
    name: streamify-frontend
    env: static
    buildCommand: cd frontend && npm ci --legacy-peer-deps && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable

  # Web Service for Backend
  - type: web
    name: streamify-backend
    env: node
    buildCommand: cd backend && npm ci --legacy-peer-deps
    startCommand: cd backend && npm start
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
